### PR TITLE
Getting the correct site_url from configuration

### PR DESCRIPTION
**Pull request by volpino**
This gets the correct site_url from the config.
Using h raised and exception while using harvesters (in our case) and probably in other configurations.

Moreover this removes unused imports

### CODE REVIEW

**Comment by volpino** [comment]
Added another commit for retrying if the file download fails. It can happen that the server is temporarly down or timeouts for some reason. It's better to retry a few times before giving up

**Comment by nigelbabu** [comment]
Hi @volpino, sorry it's taken a lot of time to get back to you. Can you tell me how `h.url_for_static('/', qualified=True)` is different from using the config? I would assume that the helper function would use the url from the config to build it anyway.

**Comment by volpino** [comment]
I don't remember exactly, I only know that the original code threw an exception and this patch fixes the issue. But after 10 months I don't really know, sorry.

**Comment by nigelbabu** [comment]
I'm going to close this issue for now. If you run into the problem again, let us know with a new issue or reopening this pull request and I'll look into it. Sorry again for delays in responding.

**Pull request closed without merging**
