### PR TITLE
Errors with strings that are 0

### PR DESCRIPTION
**Pull request by domoritz**
See http://lists.okfn.org/pipermail/ckan-dev/2013-June/005037.html

### CODE REVIEW

**Comment by domoritz** [comment]
@nigelbabu @johnglover Does someone have time to review this?

**Comment by georgepm** [comment]
Hi Dominik, Ive changed that line in the ckanext/datastorer/tasks.py (including #python setup.py develop), and tested with the same file. However, Ive got the same result.

**Comment by domoritz** [comment]
@georgepm Are you sure that the datastorer rerun? If not, change to url to something random and then back to trigger it manually or create a new resource with the same url.

**Comment by georgepm** [comment]
Hi @domoritz , what I did is to change the line with the new one (if cell.value is None:), then run $ sudo python setup.py develop, and finally run the datastorer manually:  paster --plugin=ckanext_datastorer datastore_upload --config=/etc/ckan/default/production.ini. Is this the right way?

**Comment by domoritz** [comment]
I'm getting

``` json
"records": [{"Num.": "1", "_id": 1, "Data1": "Text", "Data3": "0", "Data2": "0"}, {"Num.": "2", "_id": 2, "Data1": "0", "Data3": "Text", "Data2": "0"}, {"Num.": "3", "_id": 3, "Data1": "Text", "Data3": "", "Data2": null}, {"Num.": "4", "_id": 4, "Data1": "Text", "Data3": "Text", "Data2": "0"}, {"Num.": "5", "_id": 5, "Data1": "0", "Data3": "", "Data2": "0"}, {"Num.": "6", "_id": 6, "Data1": "0", "Data3": "", "Data2": "0"}, {"Num.": "7", "_id": 7, "Data1": "Text", "Data3": "Text", "Data2": "0"}, {"Num.": "8", "_id": 8, "Data1": "0", "Data3": "0", "Data2": "0"}, {"Num.": "9", "_id": 9, "Data1": "0", "Data3": "Text", "Data2": "0"}, {"Num.": "10", "_id": 10, "Data1": "Text", "Data3": "0", "Data2": "0"}]
```

Is that what you would expect?

Have you installed the datastorer before (with `setup.py install` or pip). In this case the old code might still be called. You can try to uninstall the datastorer with `pip uninstall ckanext-datastorer` and then run `python setup.py develop` when you are in your virtual environment. You could also try to add a log command and see whether it is printed.

**Comment by nigelbabu** [comment]
@domoritz You have to fix this in https://github.com/okfn/ckanext-datastorer/blob/master/ckanext/datastorer/commands.py#L397 as well. The reason for this code being copied is, importing tasks.py means celery needs to be installed. At a future point, they should go into another file and be imported in both places. If you want to do that now, I'd be happy to review it.

If @georgepm is using the cron script, that's why he isn't seeing the changes.

**Comment by georgepm** [comment]
Hi @domoritz , @nigelbabu, Now it works well. I have changed the commands.py file also, and then run 'python setup.py develop'. Im using the cron script. 

Thanks for your help.

**Comment by nigelbabu** [comment]
Excellent. Thanks for testing, @georgepm!

**Pull request merged**
